server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db
      database: user_db
app:
  topic:
    batch: testtopic
  kafka:
    batch:
      size: 5
    poll-interval: 3000